### ISSUE TITLE
Gravity DEX Data Extraction

### ISSUE THREAD

**Issue by dongsam** [allinbits/gravity-dex-stats#1]
current-state
- [x] liquidity reserve, each pool (accumulated)
- [x] number of kind of tokens traded on Gravity DEX (accumulated)

endblock_events
- [x] total amount swapped, each pool (period)
- [x] number of unique traders (accumulated)
- [x] total fees paid, each pool (period) : current usd price

exported-states
- [x] number of pool investors (accumulated) : each pool, total

Due date : 13 Aug
